#!/usr/bin/env python3
"""
Thumbnail Generator for 360° Panoramic Images
Generates optimized thumbnails for high-resolution images in the 'exported' directory.
"""

import os
import json
from pathlib import Path
from PIL import Image

# Configuration
SOURCE_DIR = Path('exported')
THUMB_DIR = SOURCE_DIR / 'thumbnails'
DATA_FILE = SOURCE_DIR / 'data.js'
THUMB_WIDTH = 400  # Width for thumbnails
QUALITY = 85  # JPEG quality (0-100)

def generate_thumbnails():
    """Generate thumbnails for all JPG images in the exported directory."""
    
    # Create thumbnails directory if it doesn't exist
    THUMB_DIR.mkdir(exist_ok=True)
    print(f"📁 Created/verified thumbnails directory: {THUMB_DIR}")
    
    # Find all JPG files
    image_files = sorted([f for f in SOURCE_DIR.glob('*.jpg') if f.is_file()])
    
    if not image_files:
        print("⚠️  No JPG files found in 'exported' directory")
        return
    
    print(f"🔍 Found {len(image_files)} images to process")
    
    processed_files = []
    
    for idx, image_path in enumerate(image_files, 1):
        try:
            # Skip if thumbnail already exists (optional: remove to force regeneration)
            thumb_path = THUMB_DIR / image_path.name
            
            # Open and process image
            with Image.open(image_path) as img:
                # Get original dimensions
                orig_width, orig_height = img.size
                
                # Calculate new height maintaining aspect ratio
                aspect_ratio = orig_height / orig_width
                new_height = int(THUMB_WIDTH * aspect_ratio)
                
                # Resize image
                img_resized = img.resize((THUMB_WIDTH, new_height), Image.Resampling.LANCZOS)
                
                # Save thumbnail
                img_resized.save(thumb_path, 'JPEG', quality=QUALITY, optimize=True)
                
                # Get file sizes for reporting
                orig_size = image_path.stat().st_size / (1024 * 1024)  # MB
                thumb_size = thumb_path.stat().st_size / (1024 * 1024)  # MB
                
                print(f"✅ [{idx}/{len(image_files)}] {image_path.name}")
                print(f"   Original: {orig_size:.2f}MB ({orig_width}x{orig_height})")
                print(f"   Thumbnail: {thumb_size:.2f}MB ({THUMB_WIDTH}x{new_height})")
                
                processed_files.append(image_path.name)
                
        except Exception as e:
            print(f"❌ Error processing {image_path.name}: {e}")
    
    # Generate data.js file with list of images
    generate_data_file(processed_files)
    
    print(f"\n🎉 Complete! Generated {len(processed_files)} thumbnails")

def generate_data_file(filenames):
    """Generate a JavaScript data file with the list of image filenames."""
    
    # Create JavaScript variable
    js_content = f"""// Auto-generated file list for exported panoramic images
// Generated by generate_thumbnails.py

const exportedImages = {json.dumps(filenames, indent=2)};
"""
    
    # Write to file
    with open(DATA_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"\n📝 Generated data file: {DATA_FILE}")
    print(f"   Contains {len(filenames)} image references")

if __name__ == '__main__':
    print("🚀 Starting thumbnail generation...\n")
    generate_thumbnails()
